// financial-ai-backend/prisma/seed.ts
import { PrismaClient, AssetType } from '@prisma/client'

const prisma = new PrismaClient()

const securities = [
  { symbol: 'AAPL', name: 'Apple Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ABNB', name: 'Airbnb Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ADBE', name: 'Adobe Inc.', type: 'STOCK' as AssetType },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', type: 'STOCK' as AssetType },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ASML', name: 'ASML Holding N.V.', type: 'STOCK' as AssetType },
  { symbol: 'AVGO', name: 'Broadcom Inc.', type: 'STOCK' as AssetType },
  { symbol: 'AXON', name: 'Axon Enterprise Inc.', type: 'STOCK' as AssetType },
  { symbol: 'MSFT', name: 'Microsoft Corporation', type: 'STOCK' as AssetType },
  { symbol: 'GOOG', name: 'Alphabet Inc.', type: 'STOCK' as AssetType },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', type: 'STOCK' as AssetType },
  { symbol: 'META', name: 'Meta Platforms Inc.', type: 'STOCK' as AssetType },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', type: 'STOCK' as AssetType },
  { symbol: 'TSLA', name: 'Tesla Inc.', type: 'STOCK' as AssetType },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', type: 'STOCK' as AssetType },
  { symbol: 'GS', name: 'The Goldman Sachs Group Inc.', type: 'STOCK' as AssetType },
  { symbol: 'MS', name: 'Morgan Stanley', type: 'STOCK' as AssetType },
  { symbol: 'BAC', name: 'Bank of America Corporation', type: 'STOCK' as AssetType },
  { symbol: 'C', name: 'Citigroup Inc.', type: 'STOCK' as AssetType },
  { symbol: 'WFC', name: 'Wells Fargo & Company', type: 'STOCK' as AssetType },
  { symbol: 'BLK', name: 'BlackRock Inc.', type: 'STOCK' as AssetType },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies Inc.', type: 'STOCK' as AssetType },
  { symbol: 'COF', name: 'Capital One Financial Corporation', type: 'STOCK' as AssetType },
  { symbol: 'AXP', name: 'American Express Company', type: 'STOCK' as AssetType },
  { symbol: 'DIS', name: 'The Walt Disney Company', type: 'STOCK' as AssetType },
  { symbol: 'MCD', name: "McDonald's Corporation", type: 'STOCK' as AssetType },
  { symbol: 'NKE', name: 'Nike Inc.', type: 'STOCK' as AssetType },
  { symbol: 'KO', name: 'The Coca-Cola Company', type: 'STOCK' as AssetType },
  { symbol: 'PEP', name: 'PepsiCo Inc.', type: 'STOCK' as AssetType },
  { symbol: 'MO', name: 'Altria Group Inc.', type: 'STOCK' as AssetType },
  { symbol: 'PM', name: 'Philip Morris International Inc.', type: 'STOCK' as AssetType },
  { symbol: 'BTI', name: 'British American Tobacco PLC', type: 'STOCK' as AssetType },
  { symbol: 'F', name: 'Ford Motor Company', type: 'STOCK' as AssetType },
  { symbol: 'GM', name: 'General Motors Company', type: 'STOCK' as AssetType },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', type: 'STOCK' as AssetType },
  { symbol: 'CVX', name: 'Chevron Corporation', type: 'STOCK' as AssetType },
  { symbol: 'COP', name: 'ConocoPhillips', type: 'STOCK' as AssetType },
  { symbol: 'MPC', name: 'Marathon Petroleum Corporation', type: 'STOCK' as AssetType },
  { symbol: 'PSX', name: 'Phillips 66', type: 'STOCK' as AssetType },
  { symbol: 'NEE', name: 'NextEra Energy Inc.', type: 'STOCK' as AssetType },
  { symbol: 'DUK', name: 'Duke Energy Corporation', type: 'STOCK' as AssetType },
  { symbol: 'SO', name: 'The Southern Company', type: 'STOCK' as AssetType },
  { symbol: 'EXC', name: 'Exelon Corporation', type: 'STOCK' as AssetType },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc.', type: 'STOCK' as AssetType },
  { symbol: 'BRK.A', name: 'Berkshire Hathaway Inc.', type: 'STOCK' as AssetType },
  { symbol: 'SPG', name: 'Simon Property Group Inc.', type: 'STOCK' as AssetType },
  { symbol: 'PLD', name: 'Prologis Inc.', type: 'STOCK' as AssetType },
  { symbol: 'AMT', name: 'American Tower Corporation', type: 'STOCK' as AssetType },
  { symbol: 'EQIX', name: 'Equinix Inc.', type: 'STOCK' as AssetType },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.', type: 'STOCK' as AssetType },
  { symbol: 'O', name: 'Realty Income Corporation', type: 'STOCK' as AssetType },
  { symbol: 'UNH', name: 'UnitedHealth Group Incorporated', type: 'STOCK' as AssetType },
  { symbol: 'PFE', name: 'Pfizer Inc.', type: 'STOCK' as AssetType },
  { symbol: 'JNJ', name: 'Johnson & Johnson', type: 'STOCK' as AssetType },
  { symbol: 'AZN', name: 'AstraZeneca PLC', type: 'STOCK' as AssetType },
  { symbol: 'LLY', name: 'Eli Lilly and Company', type: 'STOCK' as AssetType },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ABBV', name: 'AbbVie Inc.', type: 'STOCK' as AssetType },
  { symbol: 'AMGN', name: 'Amgen Inc.', type: 'STOCK' as AssetType },
  { symbol: 'BIIB', name: 'Biogen Inc.', type: 'STOCK' as AssetType },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', type: 'STOCK' as AssetType },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.', type: 'STOCK' as AssetType },
  { symbol: 'BA', name: 'The Boeing Company', type: 'STOCK' as AssetType },
  { symbol: 'RTX', name: 'RTX Corporation', type: 'STOCK' as AssetType },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation', type: 'STOCK' as AssetType },
  { symbol: 'GD', name: 'General Dynamics Corporation', type: 'STOCK' as AssetType },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation', type: 'STOCK' as AssetType },
  { symbol: 'CAT', name: 'Caterpillar Inc.', type: 'STOCK' as AssetType },
  { symbol: 'DE', name: 'Deere & Company', type: 'STOCK' as AssetType },
  { symbol: 'NFLX', name: 'Netflix Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ROKU', name: 'Roku Inc.', type: 'STOCK' as AssetType },
  { symbol: 'SPOT', name: 'Spotify Technology S.A.', type: 'STOCK' as AssetType },
  { symbol: 'SQ', name: 'Block Inc.', type: 'STOCK' as AssetType },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.', type: 'STOCK' as AssetType },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', type: 'STOCK' as AssetType },
  { symbol: 'OKTA', name: 'Okta Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ZOOM', name: 'Zoom Video Communications Inc.', type: 'STOCK' as AssetType },
  { symbol: 'DOCU', name: 'DocuSign Inc.', type: 'STOCK' as AssetType },
  { symbol: 'NET', name: 'Cloudflare Inc.', type: 'STOCK' as AssetType },
  { symbol: 'DDOG', name: 'Datadog Inc.', type: 'STOCK' as AssetType },
  { symbol: 'SNOW', name: 'Snowflake Inc.', type: 'STOCK' as AssetType },
  { symbol: 'CRM', name: 'Salesforce Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ORCL', name: 'Oracle Corporation', type: 'STOCK' as AssetType },
  { symbol: 'SAP', name: 'SAP SE', type: 'STOCK' as AssetType },
  { symbol: 'IBM', name: 'International Business Machines Corporation', type: 'STOCK' as AssetType },
  { symbol: 'INTC', name: 'Intel Corporation', type: 'STOCK' as AssetType },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated', type: 'STOCK' as AssetType },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', type: 'STOCK' as AssetType },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', type: 'STOCK' as AssetType },
  { symbol: 'LRCX', name: 'Lam Research Corporation', type: 'STOCK' as AssetType },
  { symbol: 'MU', name: 'Micron Technology Inc.', type: 'STOCK' as AssetType },
  { symbol: 'MCHP', name: 'Microchip Technology Incorporated', type: 'STOCK' as AssetType },
  { symbol: 'KLAC', name: 'KLA Corporation', type: 'STOCK' as AssetType },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.', type: 'STOCK' as AssetType },
  { symbol: 'SNPS', name: 'Synopsys Inc.', type: 'STOCK' as AssetType },
  { symbol: 'T', name: 'AT&T Inc.', type: 'STOCK' as AssetType },
  { symbol: 'VZ', name: 'Verizon Communications Inc.', type: 'STOCK' as AssetType },
  { symbol: 'CMCSA', name: 'Comcast Corporation', type: 'STOCK' as AssetType },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', type: 'STOCK' as AssetType },
  { symbol: 'CHTR', name: 'Charter Communications Inc.', type: 'STOCK' as AssetType },
  { symbol: 'CCI', name: 'Crown Castle International Corp.', type: 'STOCK' as AssetType },
  { symbol: 'GE', name: 'General Electric Company', type: 'STOCK' as AssetType },
  { symbol: 'HON', name: 'Honeywell International Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ETN', name: 'Eaton Corporation PLC', type: 'STOCK' as AssetType },
  { symbol: 'EMR', name: 'Emerson Electric Co.', type: 'STOCK' as AssetType },
  { symbol: 'ADSK', name: 'Autodesk Inc.', type: 'STOCK' as AssetType },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated', type: 'STOCK' as AssetType },
  { symbol: 'KEYS', name: 'Keysight Technologies Inc.', type: 'STOCK' as AssetType },
  { symbol: 'SWKS', name: 'Skyworks Solutions Inc.', type: 'STOCK' as AssetType },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software Inc.', type: 'STOCK' as AssetType },
  { symbol: 'RBLX', name: 'Roblox Corporation', type: 'STOCK' as AssetType },
  { symbol: 'EA', name: 'Electronic Arts Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ATVI', name: 'Activision Blizzard Inc.', type: 'STOCK' as AssetType },
  { symbol: 'GME', name: 'GameStop Corp.', type: 'STOCK' as AssetType },
  { symbol: 'AMC', name: 'AMC Entertainment Holdings Inc.', type: 'STOCK' as AssetType },
  { symbol: 'AIG', name: 'American International Group Inc.', type: 'STOCK' as AssetType },
  { symbol: 'PARA', name: 'Paramount Global', type: 'STOCK' as AssetType },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.', type: 'STOCK' as AssetType },
  { symbol: 'RDDT', name: 'Reddit Inc.', type: 'STOCK' as AssetType },
  { symbol: 'PSTG', name: 'Pure Storage Inc.', type: 'STOCK' as AssetType },
  { symbol: 'COIN', name: 'Coinbase Global Inc.', type: 'STOCK' as AssetType },
  { symbol: 'MSTR', name: 'MicroStrategy Incorporated', type: 'STOCK' as AssetType },
  { symbol: 'HOOD', name: 'Robinhood Markets Inc.', type: 'STOCK' as AssetType },
  { symbol: 'U', name: 'Unity Software Inc.', type: 'STOCK' as AssetType },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.', type: 'STOCK' as AssetType },
  { symbol: 'ADAUSD', name: 'Cardano', type: 'CRYPTO' as AssetType },
  { symbol: 'BTCUSD', name: 'Bitcoin', type: 'CRYPTO' as AssetType },
  { symbol: 'DOGEUSD', name: 'Dogecoin', type: 'CRYPTO' as AssetType },
  { symbol: 'ETHUSD', name: 'Ethereum', type: 'CRYPTO' as AssetType },
  { symbol: 'SOLUSD', name: 'Solana', type: 'CRYPTO' as AssetType },
  { symbol: 'XRPUSD', name: 'Ripple', type: 'CRYPTO' as AssetType },
]

async function main() {
  console.log('Starting database seed...')

  // Clear existing securities (optional - remove if you want to preserve)
  await prisma.security.deleteMany({})
  console.log('Cleared existing securities')

  // Insert all securities
  const result = await prisma.security.createMany({
    data: securities,
    skipDuplicates: true,
  })

  console.log(`Seeded ${result.count} securities`)
  await prisma.$disconnect()
}

main()
  .catch((e) => {
    console.error('Seed failed:', e)
    process.exit(1)
  })
